### ISSUE TITLE
config.reek ignored

### ISSUE THREAD

**Issue by giannileggio** [AtomLinter/linter-reek#16]
Hi guys, I installed the plugin and it's great, thanks
But it ignores the config.reek, if I run reek from the command line it works the way I want, but in Atom it ignores my configurations.

**Comment by Arcanemagus** [comment]
Looks like the simplest solution to this would be to simply pass the `cwd` of the current file to the environment that `reek` is ran under.

**Comment by giannileggio** [comment]
Thanks @Arcanemagus I don't have any experience with Atom plugins, but I'll try to have a look

**Comment by troessner** [comment]
>> Looks like the simplest solution to this would be to simply pass the cwd of the current file to the environment that reek is ran under.

and

>> Thanks @Arcanemagus I don't have any experience with Atom plugins, but I'll try to have a look

But actually this is breaking `Reek`s default behaviour, so I'd consider this a `linter-reek` bug which should be fixed upstream, e.g. here ;)

**Comment by Arcanemagus** [comment]
@troessner I'm not sure I understand what you are saying there... `reek` is currently ran under the default subprocess environment, which is usually the Atom configuration directory. Setting the current working directory for the subprocess `reek` is launched under should make it match the behavior on the command line, so I don't see how this is "breaking `Reek`s default behaviour".

@dhagerty9009 since you haven't responded I'll try to get some time to throw up a fix for this if @giannileggio doesn't beat me to it :wink:.

**Comment by dhagerty9009** [comment]
I agree with @Arcanemagus. I think the easiest solution is adding an option in the plugin's settings for a config file location. If that setting is not `null`, append the command line flag for a config file location to the command used by the subprocess.

**Comment by dhagerty9009** [comment]
Also, whoever wants to implement a fix for this, feel free.

**Comment by troessner** [comment]
@Arcanemagus i was merely referring to that this should be fixed in `linter-reek` and shouldn't be part of a configuration setting every user should have to set manually.
Which is now done via #17 - awesome job guys ;)
